### PR TITLE
Update dependencies for GPVM

### PR DESCRIPTION
**Pull request by Noah-Everett**
Will fix UPS setups and make minor changes in code to account for new versions of dependencies to allow WCSim to work plug and play (ish) on the ANNIE GPVM. The changes I will make have already been tested and work on the ANNIE GPVM.

### CODE REVIEW

**Comment by marc1uk** [comment]
Hi Noah. Thanks for the PR. I can't help but notice this seems to include "changes" in commits that go back 13 months, and have already been merged in. I'm not sure what you've done, but it looks like you've changed the git history going back quite a way. Can you rebase your changes on the current annie branch?

**Comment by marc1uk** [comment]
Also, I just realised this is on my personal github account. :sweat_smile: Please submit your PR to the [anniesoft WCSim repository](https://github.com/anniesoft/wcsim).

**Comment by Noah-Everett** [comment]
Hi Marcus. Im very sorry about this. Hopefully I didn't mess anything up too bad. To be honest, Ive never done a pull request before and I neglected to do any preemptive research on the subject before trying. If there is anything I can do to fix my mistakes, please let me know. Sorry for the inconvenience.

**Comment by marc1uk** [comment]
Hi Noah,
Don't sweat it, git has a notoriously steep learning curve (although it pays back dividends so well worth the effort to learn).
In fact, that's the whole point of Pull Requests - no changes get merged into the repository until approved, so no harm can be accidentally done (at least not unless an "expert" makes a mistake :sweat_smile: ).
The good news is that I think somehow the problem was not with the set of commits you made changing the git history, but rather the pull request you made seemed to be asking to merge the wrong branches. You need to fork your own copy of anniesoft/wcsim, push your commits to a new branch on your repository, then make a pull request from that branch on your repository to the annie branch on the anniesoft repository.

**Comment by Noah-Everett** [comment]
Okay. Ill look into that more. Thanks for all the help!

**Pull request merged**
